Replenish doc
electricbubble/gidevice pull request #18
Opened 2022-02-26 15:54 UTC by ZhouYixun

2022-02-26 16:15 UTC, electricbubble requested changes

2022-02-26 16:15 UTC, electricbubble commented on README.md
> +	listener, err := net.Listen("tcp", fmt.Sprintf(":%d", 8100))
建议将 `本地端口`/`远程端口` 提前声明

方便使用者知道两个 `8100` 的区别

```golang
localPort := 8100
remotePort := 8100
```

2022-02-26 16:42 UTC, ZhouYixun commented on README.md
> +	fmt.Println(d1)
查看最后一次提交，已经补上了

2022-02-26 16:42 UTC, ZhouYixun commented on README.md
> +	fmt.Println(d1)
前面漏了一截get

2022-02-26 16:43 UTC, ZhouYixun commented on README.md
> +			os.Exit(0)
已补上err判断

2022-02-26 16:47 UTC, electricbubble approved these changes

2022-02-26 16:50 UTC, merged

2022-02-27 04:10 UTC, ZhouYixun commented
Thanks!